# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfde85c5d024238e4e012e77f8d56493b35ebe3c4fede9366980039945f0bdc9b6b8490f5e8f2217951f1828e8da0dd6af0b2dc6849998c7b7cd3202ee54f3b

test:
  secret_key_base: f0b27d8ee609f59576dfbda0acfa1e32532a7be64c0e4604a86a88c57a20162ccfef89fdf1e9b95c8d9f856b194aa4531f007d43b0b7e2fb9090d276db24c551

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
